"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {ChevronLeft,ChevronRight,Copy,MessageCircle,Send,Share2,Sparkles} from "lucide-react";
type Line={who:string;text:string;emote?:boolean};
type Crater={x:number;r:number};
type State={positions:[number,number];hp:[number,number];turn:0|1;turnNo:number;moved:[number,number];specialUsed:[boolean,boolean];wind:number;winner:number|null;craters:Crater[];lastEvent:{type:string;player?:number;impactX?:number;angle?:number;power?:number;special?:boolean;hit?:boolean;damage?:number;nonce:number};chat:Line[]};
const quips={opening:["Tu turno. La confianza también altera la puntería.","Tu turno. El viento ya preparó su coartada.","Apunta con calma; improvisar ya viene incluido.","Tu turno. La geometría espera una explicación."],hit:["Impacto limpio. Hasta la física levantó la ceja.","Buen cálculo. El rival lo verificó personalmente.","Precisión confirmada. La modestia puede esperar.","Golpe directo. El paisaje agradece la excepción.","Eso fue puntería, no suerte. Probablemente."],miss:["El terreno recibió un mensaje que no era para él.","Buen disparo, si estabas negociando con el horizonte.","La trayectoria fue elegante. El resultado, independiente.","Fallaste con suficiente estilo para generar dudas.","El viento acepta felicitaciones, no reclamos.","La intención llegó. El proyectil tomó otra ruta."],special:["El especial fue inolvidable. El objetivo no tanto.","Mucho espectáculo; poca coincidencia geográfica.","La épica ocurrió unos metros fuera de cámara."]};
const pick=<T,>(items:T[])=>items[Math.floor(Math.random()*items.length)];
const initial:State={positions:[122,638],hp:[160,160],turn:0,turnNo:1,moved:[0,0],specialUsed:[false,false],wind:4,winner:null,craters:[],lastEvent:{type:"start",nonce:0},chat:[{who:"El Rosado",text:"En el Callao primero se apunta. Luego se discute."}]};
const groundAt=(x:number,craters:Crater[]=[])=>{let y=303+18*Math.sin(x/58)+10*Math.sin(x/27)+5*Math.sin(x/13);for(const c of craters){const d=Math.abs(x-c.x);if(d<c.r)y+=Math.sqrt(c.r*c.r-d*d)*.42}return y};
const getToken=()=>{let t=localStorage.getItem("oddbound-token");if(!t){t=crypto.randomUUID();localStorage.setItem("oddbound-token",t)}return t};
const makeCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),lastAnim=useRef(0);const [game,setGame]=useState<State>(initial),[role,setRole]=useState<0|1>(0),[room,setRoom]=useState(""),[online,setOnline]=useState(false),[waiting,setWaiting]=useState(false),[angle,setAngle]=useState(47),[power,setPower]=useState(66),[draft,setDraft]=useState(""),[chatOpen,setChatOpen]=useState(false),[notice,setNotice]=useState(()=>pick(quips.opening)),[busy,setBusy]=useState(false),[joinCode,setJoinCode]=useState(""),[walking,setWalking]=useState<[boolean,boolean]>([false,false]);
 const mine=role,theirs=(1-role) as 0|1,isMine=game.turn===mine&&game.winner===null,steps=Math.max(0,104-game.moved[mine]);const names=useMemo(()=>role===0?["Chaski","El Rosado"]:["El Rosado","Chaski"],[role]);const specialName=mine===0?"HUAYCO":"BOMBARDERO ROSADO";const craters=game.craters??[];
 const draw=useCallback((orb?:{x:number;y:number},boom?:{x:number;y:number;r:number;special?:boolean})=>{const c=canvas.current,x=c?.getContext("2d");if(!c||!x)return;const bg=new Image();bg.src="/game/lima-street.png";const paint=()=>{x.drawImage(bg,0,0,c.width,c.height);const asphalt=x.createLinearGradient(0,290,0,390);asphalt.addColorStop(0,"#697079");asphalt.addColorStop(1,"#252d38");x.fillStyle=asphalt;x.beginPath();x.moveTo(0,390);x.lineTo(0,groundAt(0,craters));for(let px=0;px<=760;px+=4)x.lineTo(px,groundAt(px,craters));x.lineTo(760,390);x.closePath();x.fill();x.strokeStyle="#c4b9a4";x.lineWidth=3;x.beginPath();for(let px=0;px<=760;px+=4){const gy=groundAt(px,craters);px?x.lineTo(px,gy):x.moveTo(px,gy)}x.stroke();x.strokeStyle="#ffffff38";x.lineWidth=2;x.setLineDash([9,12]);x.beginPath();for(let px=0;px<=760;px+=8){const gy=groundAt(px,craters)+31;px?x.lineTo(px,gy):x.moveTo(px,gy)}x.stroke();x.setLineDash([]);if(orb){x.shadowColor=boom?.special?"#c65cff":"#ffe36a";x.shadowBlur=22;x.fillStyle=boom?.special?"#b663ff":"#ffe36a";x.beginPath();x.arc(orb.x,orb.y,boom?.special?11:7,0,7);x.fill();x.shadowBlur=0}if(boom){const g=x.createRadialGradient(boom.x,boom.y,3,boom.x,boom.y,boom.r);g.addColorStop(0,"#fff");g.addColorStop(.22,boom.special?"#e58cff":"#ffe05f");g.addColorStop(.62,boom.special?"#7138df":"#ff714a");g.addColorStop(1,"#0000");x.fillStyle=g;x.beginPath();x.arc(boom.x,boom.y,boom.r,0,7);x.fill()}};bg.complete?paint():bg.onload=paint},[craters]);
 useEffect(()=>draw(),[draw,game.positions]);
 const animate=useCallback((ev:State["lastEvent"])=>{if(ev.type!=="fire"||!canvas.current)return;const player=ev.player??0,a=(ev.angle??45)*Math.PI/180,p=ev.power??60,terrain=ev.impactX===undefined?craters:craters.slice(0,-1);let x=game.positions[player],y=groundAt(x,terrain)-47,dx=Math.cos(a)*p*.145*(player===0?1:-1),dy=-Math.sin(a)*p*.145,n=0;const tick=()=>{x+=dx;y+=dy;dy+=.17;dx+=game.wind*.0016;n++;draw({x,y},{x,y,r:0,special:ev.special});if(ev.special&&player===1)draw({x:x-13,y:y+7},{x,y,r:0,special:true});if(y<groundAt(x,terrain)&&x>0&&x<760&&n<420)requestAnimationFrame(tick);else{let r=5;const pop=()=>{r+=ev.special?7:5;draw(undefined,{x,y:Math.min(y,groundAt(x,terrain)),r,special:ev.special});if(r<(ev.special?72:38))requestAnimationFrame(pop);else draw()};pop()}};tick()},[draw,game.positions,game.wind,craters]);
 useEffect(()=>{if(game.lastEvent.nonce&&game.lastEvent.nonce!==lastAnim.current){lastAnim.current=game.lastEvent.nonce;if(game.lastEvent.type==="move"&&game.lastEvent.player!==undefined){const p=game.lastEvent.player;setWalking(w=>w.map((v,i)=>i===p?true:v) as [boolean,boolean]);setTimeout(()=>setWalking(w=>w.map((v,i)=>i===p?false:v) as [boolean,boolean]),520)}animate(game.lastEvent);if(game.lastEvent.type==="fire")setNotice(game.lastEvent.hit?`${pick(quips.hit)} ${game.lastEvent.damage} de daño.`:pick(game.lastEvent.special?quips.special:quips.miss))}},[game.lastEvent,animate]);
 const post=async(payload:Record<string,unknown>,c=room)=>{const r=await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,code:c,token:getToken()})});const j=await r.json();if(!r.ok)throw new Error(j.error||"La conexión decidió tomar un descanso.");return j};
 const createRoom=async()=>{setBusy(true);const c=makeCode();try{const j=await post({action:"create"},c);setRoom(c);setRole(0);setOnline(true);setWaiting(true);setGame(j.state);history.replaceState({},"",`?room=${c}`);setNotice("Sala creada. Comparte el enlace con tu rival.")}catch(e){setNotice(e instanceof Error?e.message:"No fue posible crear la sala.")}finally{setBusy(false)}};
 const join=useCallback(async(c:string)=>{c=c.trim().toUpperCase();if(!c)return;setBusy(true);try{const r=await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"join",code:c,token:getToken()})});const j=await r.json();if(!r.ok)throw new Error(j.error);setRoom(c);setRole(j.role);setOnline(true);setWaiting(false);setGame({...j.state,craters:j.state.craters??[]});history.replaceState({},"",`?room=${c}`);setNotice(j.role===0?"Esperando al rival…":"Conectado. Demuestra que el tutorial era opcional.")}catch(e){setNotice(e instanceof Error?e.message:"No fue posible entrar.")}finally{setBusy(false)}},[]);
 useEffect(()=>{const q=new URLSearchParams(location.search).get("room");if(q)join(q)},[join]);
 useEffect(()=>{if(!online||!room)return;const id=setInterval(async()=>{try{const r=await fetch(`/api/room?code=${room}`,{cache:"no-store"});if(r.ok){const j=await r.json();setWaiting(j.waiting);setGame({...j.state,craters:j.state.craters??[]})}}catch{}},900);return()=>clearInterval(id)},[online,room]);
 const localFire=(special:boolean)=>{if(!isMine||(special&&game.specialUsed[0]))return;const terrain=game.craters??[],a=angle*Math.PI/180;let x=game.positions[0],y=groundAt(x,terrain)-47,dx=Math.cos(a)*power*.145,dy=-Math.sin(a)*power*.145;for(let i=0;i<420&&y<groundAt(x,terrain)&&x<760;i++){x+=dx;y+=dy;dy+=.17;dx+=game.wind*.0016}const impactX=Math.max(8,Math.min(752,x)),hit=Math.abs(x-game.positions[1])<(special?105:61),damage=hit?(special?44:25):0,ev={type:"fire",player:0,impactX,angle,power,special,hit,damage,nonce:Date.now()};setGame(s=>({...s,hp:[s.hp[0],Math.max(0,s.hp[1]-damage)],turn:1,turnNo:s.turnNo+1,specialUsed:[s.specialUsed[0]||special,s.specialUsed[1]],craters:[...(s.craters??[]).slice(-13),{x:impactX,r:special?22:14}],lastEvent:ev}));setTimeout(()=>setGame(s=>{if(s.hp[1]<=0)return{...s,winner:0};const hitBot=Math.random()>.55;return{...s,hp:[Math.max(0,s.hp[0]-(hitBot?25:0)),s.hp[1]],turn:0,turnNo:s.turnNo+1,moved:[0,s.moved[1]],wind:Math.round(Math.random()*24-12),lastEvent:{type:"fire",player:1,angle:48,power:62,special:false,hit:hitBot,damage:hitBot?25:0,nonce:Date.now()}}}),1300)};
 const act=async(action:string,extra:Record<string,unknown>={})=>{if(online){try{const j=await post({action,...extra});setGame({...j.state,craters:j.state.craters??[]})}catch(e){setNotice(e instanceof Error?e.message:"La acción no pudo sincronizarse.")}}else if(action==="move"){setGame(s=>{const d=Number(extra.delta),left=104-s.moved[0],actual=Math.sign(d)*Math.min(Math.abs(d),left),pos=Math.max(50,Math.min(340,s.positions[0]+actual));return{...s,positions:[pos,s.positions[1]],moved:[s.moved[0]+Math.abs(pos-s.positions[0]),s.moved[1]]}})}else if(action==="chat"||action==="emote")setGame(s=>({...s,chat:[...s.chat,{who:"Chaski",text:String(extra.text),emote:action==="emote"}]}));else if(action==="fire")localFire(Boolean(extra.special))};
 const send=()=>{if(!draft.trim())return;act("chat",{text:draft.trim()});setDraft("")};const share=async()=>{await navigator.clipboard?.writeText(`${location.origin}${location.pathname}?room=${room}`);setNotice("Enlace copiado. La diplomacia termina aquí. 📋")};const fighterStyle=(i:0|1)=>{const px=game.positions[i],tilt=Math.atan2(groundAt(px+7,craters)-groundAt(px-7,craters),14)*180/Math.PI;return{left:`${px/7.6}%`,bottom:`${Math.max(0,(389-groundAt(px,craters))/3.9)}%`,["--tilt" as string]:`${tilt}deg`}};const aimFor=(i:0|1)=>{const px=game.positions[i],gy=groundAt(px,craters),dir=i===0?1:-1,a=(i===mine?angle:48)*Math.PI/180,len=i===mine?48+power*.1:54,sx=px+dir*9,sy=gy-31,ex=sx+Math.cos(a)*len*dir,ey=sy-Math.sin(a)*len;return{sx,sy,ex,ey,cx:(sx+ex)/2,cy:(sy+ey)/2-5}};const aimGuides:[0|1,ReturnType<typeof aimFor>][]=[[0,aimFor(0)],[1,aimFor(1)]];
 return <main className="game-shell"><header className="topbar"><div className="brand"><span>✦</span><strong>LIMA BOUND</strong><i>ALPHA</i></div><div className="room"><b/> {online?`ROOM ${room}`:"PRACTICE CON BOT"}</div>{online?<button className="share" onClick={share}><Copy size={17}/> COPY LINK</button>:<button className="share" onClick={createRoom} disabled={busy}><Share2 size={17}/> INVITE 1V1</button>}</header>
 <section className="battle"><div className="hud mine"><img src={role===0?"/characters/chaski.png":"/characters/sportboys-barrista.png"} alt="your fighter"/><div><small>YOU / TÚ</small><strong>{names[0]}</strong><div className="hp"><i style={{width:`${game.hp[mine]/1.6}%`}}/></div></div></div><div className="turn"><small>TURN {String(game.turnNo).padStart(2,"0")}</small><strong>{waiting?"Esperando rival…":notice}</strong><span>Viento {game.wind>=0?"→":"←"} {Math.abs(game.wind)}</span></div><div className="hud theirs"><div><small>RIVAL / CAUSA</small><strong>{names[1]}</strong><div className="hp foe"><i style={{width:`${game.hp[theirs]/1.6}%`}}/></div></div><img src={role===0?"/characters/sportboys-barrista.png":"/characters/chaski.png"} alt="rival fighter"/></div><canvas ref={canvas} width={760} height={390}/>
 <svg className="aim-guide" viewBox="0 0 760 390" preserveAspectRatio="none" aria-label="Dirección de disparo de ambos personajes"><defs><linearGradient id="aim-red" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stopColor="#ff8b96" stopOpacity=".72"/><stop offset="1" stopColor="#ff1835"/></linearGradient><marker id="aim-arrow" viewBox="0 0 12 12" refX="10" refY="6" markerWidth="8" markerHeight="8" orient="auto"><path d="M1 1 L11 6 L1 11 L4.3 6 Z"/></marker></defs>{aimGuides.map(([i,g])=><g key={i} className={`aim-vector ${game.turn===i?"current":""}`}><circle cx={g.sx} cy={g.sy} r="3.5"/><path className="aim-shadow" d={`M ${g.sx} ${g.sy} Q ${g.cx} ${g.cy} ${g.ex} ${g.ey}`}/><path className="aim-stroke" d={`M ${g.sx} ${g.sy} Q ${g.cx} ${g.cy} ${g.ex} ${g.ey}`} markerEnd="url(#aim-arrow)"/></g>)}</svg>
 <div className={`fighter dog ${game.turn===0?"active":""} ${walking[0]?"walking":""}`} style={fighterStyle(0)}><span className="fighter-art"><img className="upper" src="/game/chaski-battle.png" alt="Chaski"/><img className="leg left" src="/game/chaski-battle.png" alt=""/><img className="leg right" src="/game/chaski-battle.png" alt=""/></span></div><div className={`fighter barrista ${game.turn===1?"active":""} ${walking[1]?"walking":""}`} style={fighterStyle(1)}><span className="fighter-art"><img className="upper" src="/game/sportboys-barrista.png" alt="El Rosado"/><img className="leg left" src="/game/sportboys-barrista.png" alt=""/><img className="leg right" src="/game/sportboys-barrista.png" alt=""/></span></div>
 {game.winner!==null&&<div className="result"><Sparkles/><strong>{game.winner===mine?"Victoria. Incluso la estadística se equivocó. 🏆":"Derrota. El viento solicita no ser culpado. 💀"}</strong><button onClick={()=>online?act("rematch"):location.reload()}>REVANCHA</button></div>}</section>
 <section className="dock"><div className="move"><div><small>MOVE / CAMINA</small><strong>{steps} m</strong><i><b style={{width:`${steps/104*100}%`}}/></i></div><button disabled={!isMine||steps===0} onClick={()=>act("move",{delta:-34})}><ChevronLeft/></button><button disabled={!isMine||steps===0} onClick={()=>act("move",{delta:34})}><ChevronRight/></button><span>Puedes cruzar cráteres y pendientes. Disparar termina el turno.</span></div><div className="aim"><label>ANGLE <b>{angle}°</b><input type="range" min="18" max="78" value={angle} onChange={e=>setAngle(+e.target.value)}/></label><label>POWER <b>{power}</b><input type="range" min="28" max="100" value={power} onChange={e=>setPower(+e.target.value)}/></label><button className="fire" disabled={!isMine||waiting} onClick={()=>act("fire",{angle,power,special:false})}>BONK<small>normal attack</small></button><button className={`special ${mine===1?"toxic":""}`} disabled={!isMine||game.specialUsed[mine]||waiting} onClick={()=>act("fire",{angle,power,special:true})}>✨ {specialName}<small>{game.specialUsed[mine]?"utilizado":"1 por partida"}</small></button></div><div className="social"><div>{["👋","😂","💀","🐸","🇵🇪"].map(e=><button key={e} onClick={()=>{act("emote",{text:e});setChatOpen(true)}}>{e}</button>)}</div><button className="chatbutton" onClick={()=>setChatOpen(v=>!v)}><MessageCircle size={18}/> Battle chat <b>{game.chat.length}</b></button><span>DEFINITIVAMENTE UN ESPORT</span></div></section>
 {!online&&<div className="joinbar"><span>¿Tienes código?</span><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/><button onClick={()=>join(joinCode)}>JOIN</button></div>}
 {chatOpen&&<aside className="chat"><header><strong>Battle chat</strong><button onClick={()=>setChatOpen(false)}>×</button></header><section>{game.chat.map((m,i)=><p key={i} className={m.emote?"emote":""}><b>{m.who}</b><span>{m.text}</span></p>)}</section><footer><input value={draft} maxLength={80} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Escribe algo ingenioso. O algo corto."/><button onClick={send}><Send size={18}/></button></footer></aside>}</main>
}
